### ISSUE TITLE
$task variable doesn't exist in @finished section

### ISSUE THREAD

**Issue by GertjanRoke** [laravel/envoy#166]
- Envoy Version: 1.6.1
- Laravel Version: 6.2.0
- PHP Version: 7.2.17

### Description:
When I run a story or task the slack hooks fires a call and that all works but I only get the default message with my name and that a task has been run, but not with the name of the story or task.

I don't know if it even works for stories, but for the task it should but doesn't in my case.

### Steps To Reproduce:
```blade
@servers(['live' => 'hostname'])

@task('test', ['on' => 'live'])
echo 'TEST!'
@endtask

@finished
@slack('https://hooks.slack.com/services/XXXX', '@gertjan')
@endfinished
```

And the end result is this:
![image](https://user-images.githubusercontent.com/6010509/67476850-254f7f80-f659-11e9-8352-1cfc56278ec4.png)

Instead of `Gertjanroke ran the [test] task.`.

**Comment by colorgreen** [comment]
`$task` variable is not defined in `@finished` scope, thats why you don't see task name.
Slack.php:74
```php        
$message = $this->message ?: ($this->task ? ucwords($this->getSystemUser()).' ran the ['.$this->task.'] task.' : ucwords($this->getSystemUser()).' ran a task.');
```
You can use `@after` section. Look this https://github.com/laravel/envoy/issues/167

**Comment by GertjanRoke** [comment]
@colorgreen But isn't it handy to also know which `@story` or `@task`  you ran inside the `@finished`?  
Because now I need to make all kinds of if statements to check which one was run to show the correct notification.

If the `$task` variable will also be available inside the `@finsihed` you don't need to think about it.

**Comment by driesvints** [comment]
Hey @GertjanRoke. If you want task specific context for your slack messages you need to define the `@slack` annotation within the task itself at the end. There is no "task" context in the `@finished` part because that's only meant to run separately at the end outside any story or task context.

The reason for this mostly is that if you have a lot of running tasks, your slack channel would be spammed every time you ran your envoy script. By adding the slack annotation specifically to the tasks you want to get info about you can selectively know which ones were run.

**Comment by driesvints** [comment]
I've sent in a PR to the docs clarify this: https://github.com/laravel/docs/pull/5568

**Comment by driesvints** [comment]
FYI: see some follow up here: https://github.com/laravel/envoy/issues/181

**Comment by arwinvdv** [comment]
`$__task` now available see https://github.com/laravel/envoy/releases/tag/v2.8.4
