### ISSUE TITLE
Support @slack and @discord in tasks

### ISSUE THREAD

**Issue by techiigg** [laravel/envoy#181]
- Envoy Version: 1.6.4
- Laravel Version: ^6.2
- PHP Version: 7.2.24

### Description:
The "finished!" message is sent through to slack. It also works without the message component e.g "<User> ran a task".

However using `@slack` inside the task (with or without message) results in this
```
[deployer@<host>]: Testing slack
[deployer@<host>]: bash: line 5: syntax error near unexpected token `$task'
[✗] This task did not complete successfully on one of your servers.
```

This works though.

```
@task('slack')
..
@endtask

@after
    @slack('webhook','test')
@endafter
```

Is there any way to stop envoy from parsing the rest of the task block as shell code? If there is then my apologies. An extra line feed doesn't seem to work atleast.

### Steps To Reproduce:
```
@task('slack')
    echo "Testing slack"
    @slack('<myactualwebhook>', 'test')
@endtask

@finished
    @slack('<myactualwebhook>', 'test', 'finished!')
@endfinished
```

envoy run --pretend slack

```
echo "Testing slack"
if (! isset($task)) $task = null; Laravel\Envoy\Slack::make('my actual webhook', 'test')->task($task)->send();
```

**Comment by driesvints** [comment]
Hey there. It turns out I was mistaken when sent in https://github.com/laravel/docs/pull/5568. The slack directive is only available for the `finished` directive.

Reason for this is because the slack directives don't start with an open and closing php tag (which is needed within a task block). The `finished` directive opens with a php tag but expects all directives within it to not have an open and closing tag. So that's why this doesn't works currently.

We could update the behavior in the future maybe so we can also place the slack and discord directives inside task blocks.

**Comment by erashdan** [comment]
+1

**Comment by driesvints** [comment]
I'm gonna close this as this is something we won't be working on ourselves anytime soon. But we're still open to prs for this.
